### ISSUE TITLE
US1. View the website sections

### ISSUE THREAD

**Issue by dm-nosov** [dm-nosov/alle-cafes#1]
## Value proposition

As a Café Owner
I want to view and edit my cafe data in the 
* About Us 
* Special Offers
* Opening Hours 
sections
so that I keep my info updated

## Description

![Image](https://github.com/dm-nosov/alle-cafes/assets/135606718/71fece43-40d6-4fcc-b5de-06438f359754)

## Acceptance criteria

- [ ] Café Owner can see the initial text (heading, paragraph, list) in 
the sections
- [ ] Café Owner can write the text (heading, paragraph, list) into 
the sections (WYSIWYG)
- [ ] Save the information to the state to change and display it to console log

## Tasks

- [ ] Create a Café page template (static semantic HTML)
- [ ] Create the new page /admin/[id]/edit
- [ ] Install the blocknotejs npm package (editor)
- [ ] Create a section editing component (wrapper around blocknotejs)
- [ ] Output the editing changes on update to console

Size: S
