### ISSUE TITLE
US6. Create a website

### ISSUE THREAD

**Issue by dm-nosov** [dm-nosov/alle-cafes#10]
## Value proposition

As a Cafe Owner
I want to create a website
so that website visitors could see it.

## Description

![Image](https://github.com/dm-nosov/alle-cafes/assets/135606718/e060bc2b-2977-4b6f-953d-1b40ad6332af)

## Acceptance criteria

- [ ] Cafe owner can create a website
- [ ] Cafe owner can cancel the create operation by dismissing a popup or by clicking Cancel
- [ ] After the creation, the new website appears in the list of the websites
- [ ] In case a client sends empty fields, the server-side validation will trigger

## Tasks

- [ ] Create a branch feature/create-website
- [ ] Update the website card to allow for the creation interface
- [ ] Implement the server-side data validation
- [ ] Save the updated values to DB and refresh the list

Size: M

**Comment by mbosselmann** [comment]
Hi Dmitry,
good job! I only have one remark: The part about the server-side validation in your last acceptance criterion is more a developer task as for the user it is not important if the validation happens client or server side. So I would suggest to mention what happens for the user if the user wants to send empty fields, for example: Will a message pop up that shows which fields are required? This should also be displayed in your wireframes. 🤔 

I hope this does help! Feel free to ask if you have further questions. :)

**Comment by mbosselmann** [comment]
LGTM! 🦊
