### ISSUE TITLE
US7. Delete website

### ISSUE THREAD

**Issue by dm-nosov** [dm-nosov/alle-cafes#11]
## Value proposition

As a Cafe Owner
I want to delete a website
so that it is no longer available to website visitors.

## Description

![image](https://github.com/dm-nosov/alle-cafes/assets/135606718/7404100e-96c6-4ccc-9910-3d4da4d8c74d)

## Acceptance criteria

- [ ] Cafe owner can delete a website
- [ ] Cafe owner can cancel the delete operation by dismissing a popup or by clicking Cancel

## Tasks

- [ ] Create a branch feature/delete-website
- [ ] Create a confirmation popup component
- [ ] Save the updated values to DB and refresh the list

Size: M
