### ISSUE TITLE
US8. View a website

### ISSUE THREAD

**Issue by dm-nosov** [dm-nosov/alle-cafes#15]
## Value proposition

As a User or Café Owner
I want to view a café website
in order to get the information about the shop.

## Description

![image](https://github.com/dm-nosov/alle-cafes/assets/135606718/78905df1-0fb2-42ed-b7ee-f76fe3daceaf)

## Acceptance criteria

- [ ] A non-authorized user sees the café website from _/public/[website-slug]/_
- [ ] A café owner sees the café website from _/public/[website-slug]/_

## Tasks

- [ ] Create the branch feature/view-website
- [ ] Create a new API route to get public data about website
- [ ] Create a new page _/public/[website-slug]/_ to display the page without the admin tools
- [ ] Insert the page title into the new page for SEO purposes
- [ ] Pre-load the new page using SSG

Size: S

**Comment by izabelladobielewska** [comment]
Looks good :)
