### ISSUE TITLE
US9. View products

### ISSUE THREAD

**Issue by dm-nosov** [dm-nosov/alle-cafes#17]
## Value proposition

As a Cafe Owner
I want to see the list of products in website content editor (/admin/[websiteId]/edit)
in order to check that the offered product positions and prices are provided correctly

## Description

![Image](https://github.com/dm-nosov/alle-cafes/assets/135606718/3993def2-f97f-4854-8385-5753deb041be)

## Acceptance criteria

- [x] The list of products is correctly displayed (prices, discounts, names, descriptions, category name)
Steps to check:
1. Create a website
2. Click the Edit icon from the website page
3. Check that the product list is displayed

## Tasks

- [x] Create the branch feature/view-products
- [x] Create the product card component
- [x] Create the category component
- [x] Add the data to the _/admin/[websiteId]/edit_ page

Size: S

**Comment by DorisW3** [comment]
Hi Dmitry,
as I can you mentioned all the important points. Maybe you can explain which "edit" button(s) is/are. 
Are the different sizes s, m, l "edit" buttons? And I don't understand what function the hyphens have.

**Comment by dm-nosov** [comment]
Hi Doris,

>Maybe you can explain which "edit" button(s) is/are.
The list will be displayed as a part of an existing editor, but since the list is static and you can only view it, please disregard all related to Edit.

>Are the different sizes s, m, l "edit" buttons? 

Here we talk about displaying a static list of products of an average cafe. A cafe hast two types of products: drinks (which vary in size) and other products (for example, a croissant). Thus, the display needs to be adjusted for both types of products.

>And I don't understand what function the hyphens have.
Hypens help you trace the line between a product name and its prices.

>if you mention which size the product has.
Products like buns, hotdogs, cakes do not have sizes

**Comment by DorisW3** [comment]
thank you for answering my questions, now I understand what you mean.
I hope could finish the US. Sorry for my late answer.
