### ISSUE TITLE
US2. Preview website sections

### ISSUE THREAD

**Issue by dm-nosov** [dm-nosov/alle-cafes#2]
## Value proposition

As a Café Owner 
I want to preview the text in the 
* About Us 
* Special Offers
* Opening Hours 
to see how my visitors will see this information

## Description

![Image](https://github.com/dm-nosov/alle-cafes/assets/135606718/209c820f-4d50-4e88-a314-8713f2cef0db)

## Acceptance criteria

- [ ] Café Owner previews the sections text /admin/[id]/preview
- [ ] Café Owner goes back to the editing mode /admin/[id]/edit

## Tasks

- [ ] Create the new page /admin/[id]/preview
- [ ] Install the zustand package to keep the sections state
- [ ] Create a switch to move between edit/preview pages in the top navigation
- [ ] Render the preview page using the state

Size: S
