### ISSUE TITLE
US10 Edit a product

### ISSUE THREAD

**Issue by dm-nosov** [dm-nosov/alle-cafes#20]
## Value proposition

As a Cafe Owner
I want to edit a product
in order to update the entered pricing and discount values

## Description

![Image](https://github.com/dm-nosov/alle-cafes/assets/135606718/acc07902-d702-4297-85a4-b5e8c4c9c9d0)

## Acceptance criteria

**❗NOTE❗**: The data update itself does not work for now, you need to check that the static data is correctly presented on the edit form.

- [ ] Check that a multi-price products are opened correctly
- [ ] Check that a single-price products are opened correctly
- [ ] Check that discounts are opened correctly
- [ ] Check that the products are correctly displayed on clicking Preview

**❗Steps to verify❗**:
1. Log in
2. Create a website
3. Click the edit icon
4. Go to the Getranke section of the site, pick random products and click "..." and select Edit

## Tasks

- [ ] Create the branch feature/edit-products
- [ ] Create the edit product card component
- [ ] Create the category component
- [ ] Add the product cards to the /admin/[websiteId]/edit page
- [ ] Update the data in the Preview mode of the /admin/[websiteId]/edit page

Size: S

**Comment by milodevhh** [comment]
LGTM - Have fun with your Tasks.
