### ISSUE TITLE
US11 Add a menu category

### ISSUE THREAD

**Issue by dm-nosov** [dm-nosov/alle-cafes#21]
## Value proposition

As a Cafe Owner
I want to add a product category
in order to organize my products

## Description

![Image](https://github.com/dm-nosov/alle-cafes/assets/135606718/8335b0b5-5e4a-485e-8c29-178ffa2d94c3)

## Acceptance criteria

- [ ] Check that initially the Menu section of _/admin/websiteId/edit_ has the form to add a category
- [ ] Check that a cafe owner adds a category
- [ ] Check that the new category appears in the Menu section with the product card inviting to add a product

**❗Steps to verify❗**:
1. Log in
2. Create a website
3. Click the edit icon on the website card
4. Go to the Menu section of the page

## Tasks

- [ ] Create the branch feature/add-category
- [ ] Create the New Product card component
- [ ] Create the New Category form component
- [ ] Create the API to add a category and get categories, /api/ws/[id]/categories 
- [ ] Update the data in the Preview mode of the /admin/[websiteId]/edit page to display the categories

Size: M

**Comment by DenisKorkmaz** [comment]
LGTM 👍🏻
