### ISSUE TITLE
US12 Delete products

### ISSUE THREAD

**Issue by dm-nosov** [dm-nosov/alle-cafes#24]
## Value proposition

As a Cafe Owner
I want to delete a product
in order to keep the actual product positions on the website 

## Description

![Image](https://github.com/dm-nosov/alle-cafes/assets/135606718/e863a115-c631-4f29-9ab6-a69119fc255a)

## Acceptance criteria

- [ ] I can delete a product
- [ ] I can cancel the delete operation

❗Steps to verify❗:

1. Log in
1. Create a website
1. Click the edit icon on the website card
1. Go to the Menu section of the page and create a category "Drinks"
1. Create a new product in the category
1. Delete the product

## Tasks

- [ ] Create the branch feature/delete-product
- [ ] Create the API to remove the products, /api/ws/[id]/products DELETE
- [ ] Add the API call to the respective product popup

Size: XS

**Comment by AndryBasaraba** [comment]
good user story!
