### ISSUE TITLE
US13. Remove a category

### ISSUE THREAD

**Issue by dm-nosov** [dm-nosov/alle-cafes#26]
## Value proposition

As a Cafe Owner
I want to delete a category
in order to keep the actual product positions on the website 

## Description

![Image](https://github.com/dm-nosov/alle-cafes/assets/135606718/77069463-4222-47b5-bea0-6050b5736370)

## Acceptance criteria

- [ ] I can delete a category
- [ ] I can cancel the delete operation

❗Steps to verify❗:

1. Log in
1. Create a website
1. Click the edit icon on the website card
1. Go to the Menu section of the page and create a category "Drinks"
1. Delete the category using the can icon

## Tasks

- [ ] Create the branch feature/remove-category
- [ ] Create the API to remove categories, /api/ws/[id]/categories/[categoryId] DELETE
- [ ] Add the API call to the respective popup

Size: S

**Comment by JudithRe** [comment]
LGTM maybe add in the AC that "products will remain" even after deleting the category - That's what you want to do right?
