### ISSUE TITLE
US14. Add Back to navigation

### ISSUE THREAD

**Issue by dm-nosov** [dm-nosov/alle-cafes#27]
## Value proposition

As a Café Owner
I want to navigate back from the editor dashboard to my other websites
in order to edit them too

## Description

![Image](https://github.com/dm-nosov/alle-cafes/assets/135606718/4e3c7547-bcd2-4e2f-b6e0-b5e3f9d71417)

## Acceptance criteria

- [ ] A user goes back to the list of websites on clicking the Back button in the editor
- [ ] criterion 2

❗Steps to verify❗:

1. Log in
1. Create a website
1. Click the edit icon on the website card
1. Go Back using the top navigation

## Tasks

- [] Create the branch _feature/add-back-to-navigation_
- [] Add the ButtonIcon components to use them instead of buttons
- [] Replace the existing buttons with icons and add the Back button which navigates back

Size: S
