### ISSUE TITLE
US3. Save sections to DB

### ISSUE THREAD

**Issue by dm-nosov** [dm-nosov/alle-cafes#3]
## Value proposition

As a Café Owner 
I want to save the text in the 
* About Us 
* Special Offers
* Opening Hours 
sections to DB
so that visitors can see this information

## Description

![Image](https://github.com/dm-nosov/alle-cafes/assets/135606718/383bd5fa-6986-46c6-bb63-b81a1853858a)

## Acceptance criteria

- [x] Café Owner sees the initial text (heading, paragraph, list) in 
the sections
- [x] Café Owner writes the text (heading, paragraph, list) into 
the sections
- [x] Café Owner saves the sections text and sees it after the page reload 

## Tasks

- [x] Create branch **feature/save-sections-to-db**
- [x] Connect to MongoDB Atlas
- [x] Create the collection "content" and fill it with the default section texts
- [x] Create the API endpoint GET **/api/ws/[id]/content** to fetch sections content
- [x] Create the API endpoint PUT **/api/ws/[id]/content** and update the content of a given website
- [x] On click Save, each section saves its data to DB
- [x] On click Preview, the page displays data from the state
- [x] Update the page **/admin/[id]/edit** to that it fetches the data from the API 

Size: M
