### ISSUE TITLE
US15. Sticky cups in preview

### ISSUE THREAD

**Issue by dm-nosov** [dm-nosov/alle-cafes#30]
## Value proposition

As a user
I want to see cup sizes only once
in order to better identify the prices in the UI

## Description

Currently every S-M-L product has own cups:

<img src="https://github.com/dm-nosov/alle-cafes/assets/135606718/0f6e43f1-3726-4cfa-80b2-c3ae206db179"  width="360"/>

The system needs to display the cup sizes only once and make them sticky:

<img src="https://github.com/dm-nosov/alle-cafes/assets/135606718/185bb4c9-9911-49a9-975f-5f6a90f121bc"  width="360"/>

## Acceptance criteria

- [ ] A Cafe Owner sees the sticky cups when they scroll the Menu section at _/admin/[wsId]/edit_ + click the eye icon.
- [ ] A user sees the sticky cups when they scroll the Menu section at _/public/[website-slug]_

## Tasks

- [ ] Create new branch feature/sticky-cups-in-preview 
- [ ] Update the category component layout

❗Steps to verify❗:

1. Log in
1. Create a website
1. Click the edit icon on the website card
1. Scroll to the Menu section
2. Create a new multi-price category
3. Add 4-5 multi-price products
4. Click the eye icon (preview)
5. Go back to the websites list and click the website slug

Size: XS

**Comment by milodevhh** [comment]
Hey Dmitry, looks good to me, have fun with the tasks.
