### ISSUE TITLE
US16. Reset the preview mode on existing the editor

### ISSUE THREAD

**Issue by dm-nosov** [dm-nosov/alle-cafes#31]
## Value proposition

As a Café Owner
I want the system to reset the preview mode when I exit the editor and start it again
in order to preserve the consistency

## Description

![Image](https://github.com/dm-nosov/alle-cafes/assets/135606718/6926f05f-67e4-40dc-bced-0d19e35b246f)

## Acceptance criteria

- [ ] I see the edit mode when I enter the editor having the _edit_ mode previously
- [ ] I see the edit mode when I enter the editor having the _preview_ previously

❗Steps to verify❗:

Log in
Create a website
Click the edit icon on the website card
Go back to the websites list 
Click the edit icon again
You must be in the edit mode (the eye icon is active)

Click the eye icon (you are in the preview mode now)
Go back to the websites list 
Click the edit icon again
You must be in the edit mode (the eye icon is active)

## Tasks

- [ ] Create branch feature/reset-ispreview-on-exit-editor
- [ ] Update the management of the isPreview state parameter on entering the _/admin/_ page

Size: XS

**Comment by alper92** [comment]
great!
