### ISSUE TITLE
US4. Log in using Facebook

### ISSUE THREAD

**Issue by dm-nosov** [dm-nosov/alle-cafes#7]
## Value proposition

As a Café Owner
I want to log in to the app using my Facebook user
in order to view the list of my Café shops.

## Description

![Image](https://github.com/dm-nosov/alle-cafes/assets/135606718/a74be9d8-f2e8-461b-80ea-97faa0060bb5)

![Image](https://github.com/dm-nosov/alle-cafes/assets/135606718/103566ce-86d0-4240-97f8-c08d3cf0597c)

## Acceptance criteria

- [ ] A Cafe Owner can log in using Facebook. Once they are authenticated, they go to the _/admin/ws_ page and see the list of their websites.
- [ ] A Cafe Owner can log out using Facebook. Once unauthenticated, they go to the main page /.

## Tasks

- [ ] create branch us11-login
- [ ] Install NextAuth.js and required dependencies (npm install next-auth).
- [ ] Create a configuration file for NextAuth.js and configure Facebook as the authentication provider.
- [ ] Generate Facebook OAuth credentials for the application and store them securely.
- [ ] Create the [...nextauth].js file inside the pages/api folder with the appropriate Facebook provider configuration.
- [ ] Set up environment variables (.env.local file) to store the OAuth credentials securely.
- [ ] Create the main page with the "Log in with FB" button.
- [ ] Implement the authentication flow using NextAuth.js to allow Cafe Owners  to log in via Facebook.
- [ ] Create the _/admin/ws_ page with the list of user's websites.

Size: L

**Comment by HannesOster** [comment]
Hey Dimitri,

Good US! For my taste its a little early for the login. Ive heard that usually the login should be the last feature.  But its your choice. :)
