### ISSUE TITLE
US5. Edit website settings

### ISSUE THREAD

**Issue by dm-nosov** [dm-nosov/alle-cafes#9]
## Value proposition

As a Cafe Owner
I want to edit the website settings (name and slug)
in order to update the information for website visitors.

## Description

![Image](https://github.com/dm-nosov/alle-cafes/assets/135606718/3985521c-7c1d-4243-a142-7bda1cfd4cac)

## Acceptance criteria

- [ ] Cafe owner can edit the website settings
- [ ] Cafe owner can cancel the edit operation by dismissing a popup or by clicking Cancel

## Tasks

- [ ] Create a branch feature/edit-website-settings
- [ ] Create a popup component
- [ ] Create extend the website card component with the editing facilities
- [ ] Save the updated values to DB

Size: M

**Comment by mbosselmann** [comment]
LGTM! :octocat:
